const SOUND_BANKS = [
  {
    id: 'heater',
    name: 'Heater Kit',
    subtitle: 'Warm analog drum machine',
    accent: 'from-amber-400 to-orange-500',
    led: 'bg-amber-400 shadow-[0_0_12px_2px_rgba(251,191,36,0.85)]',
    sounds: [
      { keyCode: 81, keyTrigger: 'Q', id: 'Heater-1', url: 'https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3' },
      { keyCode: 87, keyTrigger: 'W', id: 'Heater-2', url: 'https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3' },
      { keyCode: 69, keyTrigger: 'E', id: 'Heater-3', url: 'https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3' },
      { keyCode: 65, keyTrigger: 'A', id: 'Heater-4', url: 'https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3' },
      { keyCode: 83, keyTrigger: 'S', id: 'Clap', url: 'https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3' },
      { keyCode: 68, keyTrigger: 'D', id: 'Open-HH', url: 'https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3' },
      { keyCode: 90, keyTrigger: 'Z', id: "Kick-n'-Hat", url: 'https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3' },
      { keyCode: 88, keyTrigger: 'X', id: 'Kick', url: 'https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3' },
      { keyCode: 67, keyTrigger: 'C', id: 'Closed-HH', url: 'https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3' },
    ],
  },
  {
    id: 'piano',
    name: 'Smooth Piano Kit',
    subtitle: 'Synthesized piano notes (C4–D5)',
    accent: 'from-cyan-400 to-sky-500',
    led: 'bg-cyan-400 shadow-[0_0_12px_2px_rgba(34,211,238,0.85)]',
    sounds: [
      { keyCode: 81, keyTrigger: 'Q', id: 'Piano-C4', note: 261.63 },
      { keyCode: 87, keyTrigger: 'W', id: 'Piano-D4', note: 293.66 },
      { keyCode: 69, keyTrigger: 'E', id: 'Piano-E4', note: 329.63 },
      { keyCode: 65, keyTrigger: 'A', id: 'Piano-F4', note: 349.23 },
      { keyCode: 83, keyTrigger: 'S', id: 'Piano-G4', note: 392.00 },
      { keyCode: 68, keyTrigger: 'D', id: 'Piano-A4', note: 440.00 },
      { keyCode: 90, keyTrigger: 'Z', id: 'Piano-B4', note: 493.88 },
      { keyCode: 88, keyTrigger: 'X', id: 'Piano-C5', note: 523.25 },
      { keyCode: 67, keyTrigger: 'C', id: 'Piano-D5', note: 587.33 },
    ],
  },
  {
    id: 'perc',
    name: '808 Percussion Kit',
    subtitle: 'Synthesized drum kit',
    accent: 'from-rose-400 to-pink-500',
    led: 'bg-rose-400 shadow-[0_0_12px_2px_rgba(251,113,133,0.85)]',
    sounds: [
      { keyCode: 81, keyTrigger: 'Q', id: 'Kick', synth: 'kick' },
      { keyCode: 87, keyTrigger: 'W', id: 'Snare', synth: 'snare' },
      { keyCode: 69, keyTrigger: 'E', id: 'Hat-C', synth: 'hat-closed' },
      { keyCode: 65, keyTrigger: 'A', id: 'Hat-O', synth: 'hat-open' },
      { keyCode: 83, keyTrigger: 'S', id: 'Tom-Hi', synth: 'tom-high' },
      { keyCode: 68, keyTrigger: 'D', id: 'Tom-Lo', synth: 'tom-low' },
      { keyCode: 90, keyTrigger: 'Z', id: 'Clap', synth: 'clap' },
      { keyCode: 88, keyTrigger: 'X', id: 'Cowbell', synth: 'cowbell' },
      { keyCode: 67, keyTrigger: 'C', id: 'Cymbal', synth: 'cymbal' },
    ],
  },
  {
    id: 'fx',
    name: 'FX Lab Kit',
    subtitle: 'Synthesized sci-fi sound effects',
    accent: 'from-violet-400 to-fuchsia-500',
    led: 'bg-violet-400 shadow-[0_0_12px_2px_rgba(167,139,250,0.85)]',
    sounds: [
      { keyCode: 81, keyTrigger: 'Q', id: 'Boom', fx: 'boom' },
      { keyCode: 87, keyTrigger: 'W', id: 'Sub', fx: 'sub' },
      { keyCode: 69, keyTrigger: 'E', id: 'Riser', fx: 'riser' },
      { keyCode: 65, keyTrigger: 'A', id: 'Reverse', fx: 'reverse' },
      { keyCode: 83, keyTrigger: 'S', id: 'Laser', fx: 'laser' },
      { keyCode: 68, keyTrigger: 'D', id: 'Glitch', fx: 'glitch' },
      { keyCode: 90, keyTrigger: 'Z', id: 'Robot', fx: 'robot' },
      { keyCode: 88, keyTrigger: 'X', id: 'Pluck', fx: 'pluck' },
      { keyCode: 67, keyTrigger: 'C', id: 'Cosmic', fx: 'cosmic' },
    ],
  },
];

export default SOUND_BANKS;